### ISSUE TITLE
Bug: Restart button causes animation speed to increase in Calligra activity

### ISSUE THREAD

**Issue by rahulshendre** [llaske/sugarizer#1862]
Clicking the restart button during the demo animation causes the drawing to speed up because multiple animations run simultaneously.

Steps to Reproduce
1. Open the Calligra activity
2. Wait for the demo animation to start
3. Click the restart button while the animation is playing
4. Observe the animation speed, it sped up a lot 

Expected Behavior
The animation should restart from the beginning at normal speed.

Actual Behavior
The animation speeds up because the previous animation continues while a new one starts, causing both to draw simultaneously.

Cause
The startDemoMode() function creates a chain of setTimeout calls stored in vm.current.timeout. When the restart button is clicked, it calls startDemoMode() again without clearing the existing timeout. This leaves the old animation chain running while a new one starts, resulting in both animations drawing to the canvas at the same time.

Proposed Fix
Add timeout cleanup at the start of startDemoMode():

Ensuring that any running animation is stopped before starting a new one, which will prevent the speed increase issue.

Additional Notes
This fix should be applied in startDemoMode() rather than just the restart button handler, as startDemoMode() is also called from init() and activity.js, there too the same issue occurs.

Video - 
https://github.com/user-attachments/assets/fefbe4c8-9624-4c9d-810e-758286533d6e

**Comment by rahulshendre** [comment]
@llaske do let me know if you were able to reproduce the issue.
I have fixed it, will send in the PR after your approval.

**Comment by llaske** [comment]
Look like more to a funny tips, not to an issue

**Comment by rahulshendre** [comment]
I see your point — at first glance it looks harmless.
However, this behavior comes from overlapping demo runs, which can leave the activity in an inconsistent state.

As shown in the video, the same issue appears when switching letters, which kids tend to do, and in some interaction timings the demo never starts again unless the activity is reloaded.

So while the speed-up may look funny. the underlying issue is that previous demo timeouts are not cleared, which can cause the demo logic to break depending on user actions.

<img width="1280" height="606" alt="Image" src="https://github.com/user-attachments/assets/dd5fe21a-3fe1-4894-971d-c5e23c8fc653" />

**Comment by llaske** [comment]
I didn't reproduce the "the demo never starts again".
So I still not see a bug here.
