### ISSUE TITLE
Firefox: Cannot close Constellation Activity when launched locally

### ISSUE THREAD

**Issue by AndreaGon** [llaske/sugarizer#688]
I came across this error when I tried closing Constellation Activity on Firefox:

![const](https://user-images.githubusercontent.com/44361130/76490568-77593c00-6466-11ea-9b17-9c4209a86f43.gif)

This only appears when launched locally.

**Comment by sarthak-g** [comment]
@AndreaGon , it is working fine.See:
![ezgif com-video-to-gif(5)](https://user-images.githubusercontent.com/42293606/76492642-baabae80-6456-11ea-9744-50c84b04ffc9.gif)

you can clear cache and then try again

**Comment by AndreaGon** [comment]
@sarthak-g Will try. Thanks :)

**Comment by AndreaGon** [comment]
Hmm, I tried it and it still doesn't work. I'm using Firefox 74.0

Here's the error log I encountered:

`NotFoundError: The operation failed because the requested database object could not be found. For example, an object store did not exist but was being opened.`

**Comment by llaske** [comment]
@AndreaGon Are you using Firefox in Private mode?
There is an issue related to this: https://github.com/llaske/sugarizer/issues/361

**Comment by AndreaGon** [comment]
@llaske No, I am not using Firefox on Private mode. It must be something in my browser, but I'm not sure.

**Comment by sarthak-g** [comment]
@AndreaGon other activities are working fine?

**Comment by llaske** [comment]
@AndreaGon Just upgraded to Firefox 74.0. Don't have the problem.

Sounds related to storage and more precisely from an error with [IndexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) storage. If it comes from this, every time you will try to write in the Journal, you should have the same issue. So every activity should do the same.
But if the IndexedDB is corrupted, cleaning your cache should solve the issue.

**Comment by AndreaGon** [comment]
@llaske I tried clearing my cache and re-installing Sugarizer. The error still persists.

I don't know why the error only shows on my side, I must've unknowingly done something on my browser. I will close this issue as it only persist on my side. Thanks for the help!
